// All emojis as actual UTF-8 characters
// This avoids unicode escape issues in JSX attributes
export const E = {
  camera: '📸',
  heart: '❤️',
  trash: '🗑️',
  timer: '⏱️',
  zap: '⚡',
  disk: '💾',
  trophy: '🏆',
  medal: '🏅',
  target: '🎯',
  fire: '🔥',
  rocket: '🚀',
  gem: '💎',
  crown: '👑',
  star: '⭐',
  muscle: '💪',
  wave: '👋',
  party: '🎉',
  lock: '🔒',
  gear: '⚙️',
  search: '🔍',
  folder: '📁',
  openFolder: '📂',
  calendar: '📅',
  phone: '📱',
  clock: '🕑',
  refresh: '🔄',
  share: '📤',
  bulb: '💡',
  sparkle: '✨',
  check: '✅',
  cross: '✕',
  plus: '➕',
  leftPoint: '👈',
  rightPoint: '👉',
  arrowUp: '⬆️',
  arrowDown: '⬇️',
  undo: '↩️',
  skip: '⏭️',
  eye: '👁',
  numbers: '🔢',
};
